# Generated by Django 3.2.6 on 2021-08-30 15:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('week_days', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('saturday', 'saturday'), ('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=56, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('am_or_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
            ],
            options={
                'ordering': ['time', 'am_or_pm', 'id'],
                'unique_together': {('time', 'am_or_pm')},
            },
        ),
        migrations.CreateModel(
            name='DoctorClinicTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_time_slot.clinic')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor_time_slot.timeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='end_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_end_time', to='doctor_time_slot.timeslot'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='start_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_start_time', to='doctor_time_slot.timeslot'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
