# Generated by Django 3.2.6 on 2021-08-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_time_slot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='user',
        ),
    ]
