# Generated by Django 3.2.6 on 2021-08-30 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor_time_slot', '0002_remove_clinic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='user',
            field=models.ManyToManyField(through='doctor_time_slot.DoctorClinicTimeSlot', to=settings.AUTH_USER_MODEL),
        ),
    ]
