# Generated by Django 3.2.6 on 2021-08-30 17:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor_time_slot', '0003_clinic_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorclinictimeslot',
            unique_together={('user', 'clinic', 'time_slot')},
        ),
    ]
