# Generated by Django 3.2.6 on 2021-08-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_time_slot', '0004_alter_doctorclinictimeslot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorclinictimeslot',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorclinictimeslot',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
