# Generated by Django 3.2.6 on 2021-08-30 18:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor_time_slot', '0005_auto_20210830_1757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorclinictimeslot',
            unique_together={('user', 'clinic', 'time_slot', 'is_deleted')},
        ),
    ]
