# Generated by Django 3.2.6 on 2021-08-30 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor_time_slot', '0003_clinic_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_clinic_appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor_time_slot.doctorclinictimeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_reservation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
