# Generated by Django 3.2.6 on 2021-08-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_reservation', '0002_auto_20210830_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
