# Generated by Django 3.2.6 on 2021-08-30 18:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_time_slot', '0006_alter_doctorclinictimeslot_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_reservation', '0003_auto_20210830_1757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'doctor_clinic_appointment', 'deleted_at')},
        ),
    ]
